### ISSUE TITLE
Missing pcl.ply file

### ISSUE THREAD

**Issue by zhigangjiang** [EnriqueSolarte/direct_360_FPE#2]
HI, thank your for your great work.

I tried to run your project, but could not find the pcl.ply file, for example in [Pilot scenes](https://drive.google.com/drive/folders/1kO_rvAAJ4y4HuBN-PczhMw6Yb1cBPvx7?usp=share_link).

The pcl.plyfile is indicated at https://github.com/EnriqueSolarte/direct_360_FPE/blob/7270a9dc7071921d080bad49bacc9c88e5cc6708/data_manager/data_manager.py#L71

**Comment by EnriqueSolarte** [comment]
Hi, 
Thanks for your feedback. 
I fixed this issue. 
1. I uploaded the missing `pcl.ply` files to the [MP3D-FPE dataset](https://drive.google.com/drive/u/2/folders/1IAHHnr5c9x9YXIizLqRigsCMlfTW1Eer) (google drive). Note that these are `*.zip` files.  
2. The [data/mp3d_fpe_google_drive_ids.csv](https://github.com/EnriqueSolarte/direct_360_FPE/blob/master/data/mp3d_fpe_google_drive_ids.csv) has been updated. The `*_pcl_ply.zip` files were added, so you can download the whole dataset running:
```
python download_mp3d_fpe.py
```
3. I created [data/mp3d_fpe_google_drive__pcl_ply__ids.csv](https://github.com/EnriqueSolarte/direct_360_FPE/blob/master/data/mp3d_fpe_google_drive__pcl_ply__ids.csv) to refer only to the missing `pcl.ply` files. You can download this data as follows:
```
python download_mp3d_fpe.py --ids_file data/mp3d_fpe_google_drive__pcl_ply__ids.csv
```
Please, let me know if you can run 360-DFPE successfully.
